# Generated by Django 4.2.5 on 2023-10-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaSuddhi', '0003_cliente_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
