# Generated by Django 4.2.5 on 2023-09-29 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaSuddhi', '0003_contactrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
