# Generated by Django 4.2.5 on 2023-09-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaSuddhi', '0004_remove_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
