# Generated by Django 4.2.5 on 2023-10-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaSuddhi', '0005_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
