# Generated by Django 4.2.5 on 2023-10-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaSuddhi', '0006_producto_delete_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
