# Generated by Django 4.2.5 on 2023-10-02 17:57

import PaginaSuddhi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaSuddhi', '0007_alter_cliente_avatar_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=PaginaSuddhi.models.directorio_imagen_avatar),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=PaginaSuddhi.models.directorio_imagen_avatar),
        ),
    ]
