# Generated by Django 4.2.5 on 2023-10-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaSuddhi', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
    ]
