# Generated by Django 4.2.5 on 2023-10-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaSuddhi', '0011_alter_avatar_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
