# Generated by Django 4.2.5 on 2023-10-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaSuddhi', '0012_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
    ]
